### ISSUE TITLE
Provide support for Chef connectivity re: policy items created by chef-provisioning-aws

### ISSUE THREAD

**Issue by jedugas** [CLEAResult/chef-aws-vpc#3]
When creating certain AWS entities such as VPCs, Chef generates special data_bags that it uses as look-ups:

https://github.com/chef/chef-provisioning-aws#aws_object
https://github.com/chef/chef-provisioning-aws#lookup_options

These simplify the code, but do require Chef credential files and a Chef configuration file (knife.rb) to map the locations of the credential information. Once a developer has configured a Chef account, a knife.rb with ENVironment variable references is one simple solution.

**Comment by nspottsie** [comment]
This cookbook assumes that the developer has an existing knife.rb (likely at ~/.chef/knife.rb) that controls their Chef credentials separately. See the following check-in which removes the knife.rb from this repository: https://github.com/CLEAResult/chef-aws-vpc/commit/9fbd2075c3b9240ccf94945ad5966a70f6b6a45d
